use anyhow::{bail, Result};
use colored::Colorize;
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};

use crate::{
    config, git, github,
    state::{MergesState, Strategy},
};

pub async fn run(stacked: bool, independent: bool) -> Result<()> {
    let root = git::repo_root()?;
    let mut state = MergesState::load(&root)?;

    if state.chunks.is_empty() {
        bail!("No chunks defined. Run `merges split` first.");
    }

    // Determine strategy for this run
    let strategy = if stacked {
        Strategy::Stacked
    } else if independent {
        Strategy::Independent
    } else {
        state.strategy.clone()
    };

    println!(
        "{} Pushing {} chunk(s) as {} PRs",
        "→".blue().bold(),
        state.chunks.len().to_string().yellow(),
        format!("{}", strategy).cyan()
    );

    let token = config::github_token()?;
    let gh = github::client(&token)?;

    let current_branch = git::current_branch(&root)?;
    let mp = MultiProgress::new();
    let spinner_style = ProgressStyle::default_spinner()
        .template("{spinner} {msg}")
        .unwrap();

    let mut current_stacked_base = state.base_branch.clone();

    // First pass: Refresh status and identify active chunks
    let mut chunk_statuses = Vec::new();
    for chunk in &state.chunks {
        let mut status = chunk.status.clone();
        if let Some(pr_number) = chunk.pr_number {
            if let Ok(info) = github::get_pr_info(&gh, &state.repo_owner, &state.repo_name, pr_number).await {
                if info.is_merged {
                    status = crate::state::ChunkStatus::Merged;
                } else if info.state == "closed" {
                    status = crate::state::ChunkStatus::Closed;
                } else {
                    status = crate::state::ChunkStatus::Pending;
                }
            }
        }
        chunk_statuses.push(status);
    }

    // Update state with new statuses
    let mut state_changed = false;
    for (i, status) in chunk_statuses.iter().enumerate() {
        if state.chunks[i].status != *status {
            state.chunks[i].status = status.clone();
            state_changed = true;
        }
    }
    if state_changed {
        state.save(&root)?;
    }

    let active_indices: Vec<usize> = chunk_statuses.iter().enumerate()
        .filter(|(_, s)| **s == crate::state::ChunkStatus::Pending)
        .map(|(i, _)| i)
        .collect();

    let total_active = active_indices.len();

    if total_active == 0 {
        println!("{} No active chunks to push.", "✓".green());
        return Ok(());
    }

    for (active_idx, &i) in active_indices.iter().enumerate() {
        let chunk = state.chunks[i].clone();
        let pb = mp.add(ProgressBar::new_spinner());
        pb.set_style(spinner_style.clone());
        pb.enable_steady_tick(std::time::Duration::from_millis(80));
        pb.set_message(format!("[{}] Syncing…", chunk.name));

        // Switch to chunk branch and sync with base
        // In worktree mode, operate in the chunk's worktree dir — no branch checkout needed.
        let work_dir = if state.use_worktrees {
            git::worktree_path(&root, &chunk.branch)
        } else {
            git::checkout(&root, &chunk.branch)?;
            root.clone()
        };
        pb.set_message(format!("[{}] Rebasing onto '{}'…", chunk.name, state.base_branch));
        match strategy {
            Strategy::Stacked => git::fetch_and_rebase_stacked(&work_dir, &state.base_branch)?,
            Strategy::Independent => git::fetch_and_rebase(&work_dir, &state.base_branch)?,
        }

        // Push
        pb.set_message(format!("[{}] Pushing…", chunk.name));
        git::push_branch(&work_dir, &chunk.branch)?;

        // Determine base for this PR
        let pr_base = match strategy {
            Strategy::Stacked => current_stacked_base.clone(),
            Strategy::Independent => state.base_branch.clone(),
        };

        // Build PR body
        let files_list = chunk.files.iter().map(|f| format!("- `{}`", f)).collect::<Vec<_>>().join("\n");
        let body = format!(
            "## Chunk {}/{}: {}\n\n**Strategy:** {}\n\n### Files included\n{}\n\n---\n*Generated by [merges](https://github.com/merges-cli/merges)*",
            active_idx + 1,
            total_active,
            chunk.name,
            strategy,
            files_list
        );

        let title = {
            let body = format!("[{}/{}] {}", active_idx + 1, total_active, chunk.name);
            // Explicit commit_prefix overrides auto-detection
            match &state.commit_prefix {
                Some(p) => format!("{} {}", p, body),
                None => git::pr_title(&state.source_branch, &body),
            }
        };

        let pr_info = if let Some(pr_number) = chunk.pr_number {
            Some((pr_number, chunk.pr_url.clone().unwrap_or_default()))
        } else {
            // Check if PR already exists on GitHub for this branch
            pb.set_message(format!("[{}] Checking for existing PR…", chunk.name));
            github::find_pr_for_branch(&gh, &state.repo_owner, &state.repo_name, &chunk.branch).await?
        };

        if let Some((pr_number, pr_url)) = pr_info {
            // PR exists — update it
            pb.set_message(format!("[{}] Updating PR #{}…", chunk.name, pr_number));
            github::update_pr(
                &gh,
                &state.repo_owner,
                &state.repo_name,
                pr_number,
                &pr_base,
                &title,
                &body,
            )
            .await?;

            if chunk.pr_number.is_none() {
                // Recovered PR number from GitHub
                state.chunks[i].pr_number = Some(pr_number);
                state.chunks[i].pr_url = Some(pr_url.clone());
                state.save(&root)?;
            }

            pb.finish_with_message(format!(
                "{} [{}] PR #{} updated → {}",
                "✓".green(),
                chunk.name.cyan(),
                pr_number,
                pr_url.dimmed()
            ));
        } else {
            // Create new PR
            pb.set_message(format!("[{}] Creating PR…", chunk.name));
            let (pr_number, pr_url) = github::create_pr(
                &gh,
                &state.repo_owner,
                &state.repo_name,
                &title,
                &chunk.branch,
                &pr_base,
                &body,
            )
            .await?;

            state.chunks[i].pr_number = Some(pr_number);
            state.chunks[i].pr_url = Some(pr_url.clone());
            state.strategy = strategy.clone();
            state.save(&root)?;

            pb.finish_with_message(format!(
                "{} [{}] PR #{} created → {}",
                "✓".green(),
                chunk.name.cyan(),
                pr_number,
                pr_url.dimmed()
            ));
        }

        // Update stacked base for next chunk if applicable
        if strategy == Strategy::Stacked {
            current_stacked_base = chunk.branch.clone();
        }
    }

    // In classic mode, return to the original branch
    if !state.use_worktrees {
        git::checkout(&root, &current_branch)?;
    }

    println!("\n{} All chunks pushed successfully!", "✓".green().bold());
    println!("  Run {} to see PR status.", "merges status".bold());

    Ok(())
}
